name: mh CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install deps
      run: sudo make deb-install-deps
    - name: make mh
      run: make mh
    - name: make test
      run: make test
  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for Homebrew
      run: |
        if test ! $(which brew); then
          echo "Homebrew not found"
          exit 1
        fi
    - name:
      run: brew update
    - name:
      run: brew install pcre2 cmocka
    - name: build
      run: make mh
