name: mh CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install deps
      run: sudo make deb-install-deps
    - name: make mh
      run: make mh
    - name: make test
      run: make test
  build-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check for Homebrew
      run: |
        if test ! $(which brew); then
          echo "Homebrew not found"
          exit 1
        fi
    - name: update brew
      run: brew update
    - name: install libs
      run: brew install pcre2 cmocka
    - name: Install dependencies
      run: |
        brew install llvm
        echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> $GITHUB_ENV
        echo 'export LDFLAGS="-L/usr/local/opt/llvm/lib"' >> $GITHUB_ENV
        echo 'export CPPFLAGS="-I/usr/local/opt/llvm/include"' >> $GITHUB_ENV
    - name: build
      run: |
         clang -o mh -D VERSION=\"aa30377\" queue.c mh.c main.c -Wall $(pkg-config --cflags --libs libpcre2-8)
